export const data = [
  {
    id: "001",
    title: "AI-Powered Resume",
    description:
      "Craft a standout resume effortlessly with our AI-driven tools.",
    icon: "<FileText />",
  },
  {
    id: "002",
    title: "Skill Enhancement Hub",
    description: "Boost your career with our curated learning paths. ",
    icon: "<BookOpen />",
  },
  {
    id: "003",
    title: "Networking Platform",
    description:
      "Expand your professional network with our intuitive platform.",
    icon: "<Users />",
  },
];

export const jobData = [
  {
    key: 1,
    company_name: "Tech Solutions Inc.",
    job_title: "Full Stack Developer",
    job_type: "Full Time",
    experience_level: "Mid-Level",
    job_description:
      "Responsible for developing and maintaining web applications using MERN stack.",
    time_stamp: "2 hours ago",
    location: "New York, NY",
  },
  {
    key: 2,
    company_name: "InnovateX",
    job_title: "Frontend Developer",
    job_type: "Internship",
    experience_level: "Entry-Level",
    job_description:
      "Assist in the development of the user interface for web applications.",
    time_stamp: "4 hours ago",
    location: "San Francisco, CA",
  },
  {
    key: 3,
    company_name: "Digital Wave",
    job_title: "Backend Developer",
    job_type: "Full Time",
    experience_level: "Senior-Level",
    job_description:
      "Lead backend development and ensure scalability of applications.",
    time_stamp: "1 day ago",
    location: "Chicago, IL",
  },
  {
    key: 4,
    company_name: "Alpha Corp",
    job_title: "React Developer",
    job_type: "Full Time",
    experience_level: "Mid-Level",
    job_description: "Develop and maintain web applications using React.js.",
    time_stamp: "3 days ago",
    location: "Seattle, WA",
  },
  {
    key: 5,
    company_name: "Beta Technologies",
    job_title: "UI/UX Designer",
    job_type: "Internship",
    experience_level: "Entry-Level",
    job_description:
      "Design user interfaces and improve user experience for web applications.",
    time_stamp: "5 days ago",
    location: "Austin, TX",
  },
  {
    key: 6,
    company_name: "Code Ninjas",
    job_title: "Software Engineer",
    job_type: "Full Time",
    experience_level: "Junior-Level",
    job_description:
      "Contribute to software development projects and learn from senior developers.",
    time_stamp: "1 week ago",
    location: "Boston, MA",
  },
  {
    key: 7,
    company_name: "DevMasters",
    job_title: "Node.js Developer",
    job_type: "Full Time",
    experience_level: "Senior-Level",
    job_description: "Develop and maintain server-side logic using Node.js.",
    time_stamp: "1 week ago",
    location: "Los Angeles, CA",
  },
  {
    key: 8,
    company_name: "Tech Frontier",
    job_title: "JavaScript Developer",
    job_type: "Full Time",
    experience_level: "Mid-Level",
    job_description:
      "Create interactive web applications using JavaScript and frameworks.",
    time_stamp: "2 weeks ago",
    location: "Denver, CO",
  },
  {
    key: 9,
    company_name: "NextGen Solutions",
    job_title: "Intern Developer",
    job_type: "Internship",
    experience_level: "Entry-Level",
    job_description: "Support software development teams in various projects.",
    time_stamp: "2 weeks ago",
    location: "Phoenix, AZ",
  },
  {
    key: 10,
    company_name: "BlueTech",
    job_title: "Full Stack Intern",
    job_type: "Internship",
    experience_level: "Entry-Level",
    job_description:
      "Work on full stack development projects under senior developer guidance.",
    time_stamp: "3 weeks ago",
    location: "Miami, FL",
  },
  {
    key: 11,
    company_name: "Web Solutions",
    job_title: "Weekend Support Engineer",
    job_type: "Weekend",
    experience_level: "Mid-Level",
    job_description:
      "Provide technical support for web applications over the weekend.",
    time_stamp: "1 month ago",
    location: "Portland, OR",
  },
  {
    key: 12,
    company_name: "Alpha Innovates",
    job_title: "Data Analyst",
    job_type: "Full Time",
    experience_level: "Junior-Level",
    job_description: "Analyze and interpret data to provide business insights.",
    time_stamp: "1 month ago",
    location: "Philadelphia, PA",
  },
  {
    key: 13,
    company_name: "TechnoSoft",
    job_title: "DevOps Engineer",
    job_type: "Full Time",
    experience_level: "Senior-Level",
    job_description:
      "Manage and improve CI/CD pipelines and cloud infrastructure.",
    time_stamp: "1 month ago",
    location: "Dallas, TX",
  },
  {
    key: 14,
    company_name: "Global Tech",
    job_title: "Project Manager",
    job_type: "Full Time",
    experience_level: "Mid-Level",
    job_description:
      "Oversee and manage web development projects from start to finish.",
    time_stamp: "2 months ago",
    location: "Atlanta, GA",
  },
  {
    key: 15,
    company_name: "Tech Solutions Inc.",
    job_title: "Quality Assurance Engineer",
    job_type: "Full Time",
    experience_level: "Mid-Level",
    job_description:
      "Ensure the quality and reliability of web applications through testing.",
    time_stamp: "2 months ago",
    location: "New York, NY",
  },
  {
    key: 16,
    company_name: "Digital Horizons",
    job_title: "AI Developer",
    job_type: "Full Time",
    experience_level: "Senior-Level",
    job_description:
      "Develop AI solutions and integrate them into web applications.",
    time_stamp: "2 months ago",
    location: "San Jose, CA",
  },
  {
    key: 17,
    company_name: "UrbanTech",
    job_title: "Cloud Engineer",
    job_type: "Full Time",
    experience_level: "Mid-Level",
    job_description: "Manage and maintain cloud services and architecture.",
    time_stamp: "3 months ago",
    location: "Houston, TX",
  },
  {
    key: 18,
    company_name: "NetSolutions",
    job_title: "Security Analyst",
    job_type: "Full Time",
    experience_level: "Mid-Level",
    job_description:
      "Ensure the security of web applications and company data.",
    time_stamp: "3 months ago",
    location: "San Diego, CA",
  },
  {
    key: 19,
    company_name: "CodePulse",
    job_title: "Mobile App Developer",
    job_type: "Full Time",
    experience_level: "Junior-Level",
    job_description:
      "Develop mobile applications for iOS and Android platforms.",
    time_stamp: "3 months ago",
    location: "Raleigh, NC",
  },
  {
    key: 20,
    company_name: "Tech Gurus",
    job_title: "Systems Administrator",
    job_type: "Full Time",
    experience_level: "Mid-Level",
    job_description:
      "Maintain and support company servers and IT infrastructure.",
    time_stamp: "4 months ago",
    location: "Detroit, MI",
  },
  {
    key: 21,
    company_name: "Web Innovators",
    job_title: "SEO Specialist",
    job_type: "Full Time",
    experience_level: "Entry-Level",
    job_description:
      "Optimize web content for search engines and improve website ranking.",
    time_stamp: "4 months ago",
    location: "San Antonio, TX",
  },
];
